CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE careers (
    "Id" uuid NOT NULL,
    "Code" character varying(30) NOT NULL,
    "Name" character varying(120) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_careers" PRIMARY KEY ("Id")
);

CREATE TABLE courses (
    "Id" uuid NOT NULL,
    "Code" character varying(30) NOT NULL,
    "Name" character varying(180) NOT NULL,
    "Department" character varying(120) NOT NULL,
    "Credits" smallint,
    CONSTRAINT "PK_courses" PRIMARY KEY ("Id")
);

CREATE TABLE roles (
    "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(30) NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Email" character varying(180) NOT NULL,
    "PasswordHash" character varying(256) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE curriculum_versions (
    "Id" uuid NOT NULL,
    "CareerId" uuid NOT NULL,
    "VersionCode" character varying(30) NOT NULL,
    "DisplayName" character varying(120) NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_curriculum_versions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_curriculum_versions_careers_CareerId" FOREIGN KEY ("CareerId") REFERENCES careers ("Id") ON DELETE RESTRICT
);

CREATE TABLE course_equivalences (
    "Id" uuid NOT NULL,
    "SourceCourseId" uuid NOT NULL,
    "TargetCourseId" uuid NOT NULL,
    "EquivalenceType" character varying(20) NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "Notes" character varying(255),
    pair_left uuid GENERATED ALWAYS AS (LEAST("SourceCourseId", "TargetCourseId")) STORED NOT NULL,
    pair_right uuid GENERATED ALWAYS AS (GREATEST("SourceCourseId", "TargetCourseId")) STORED NOT NULL,
    CONSTRAINT "PK_course_equivalences" PRIMARY KEY ("Id"),
    CONSTRAINT ck_course_equivalences_not_same CHECK ("SourceCourseId" <> "TargetCourseId"),
    CONSTRAINT "FK_course_equivalences_courses_SourceCourseId" FOREIGN KEY ("SourceCourseId") REFERENCES courses ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_course_equivalences_courses_TargetCourseId" FOREIGN KEY ("TargetCourseId") REFERENCES courses ("Id") ON DELETE RESTRICT
);

CREATE TABLE directors (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DirectorCode" character varying(30) NOT NULL,
    "FullName" character varying(160) NOT NULL,
    "Campus" character varying(120),
    CONSTRAINT "PK_directors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_directors_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE professors (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ProfessorCode" character varying(30) NOT NULL,
    "FullName" character varying(160) NOT NULL,
    "Department" character varying(120) NOT NULL,
    "Speciality" character varying(120),
    CONSTRAINT "PK_professors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_professors_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(256) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByTokenHash" character varying(256),
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_refresh_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE students (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "StudentCode" character varying(30) NOT NULL,
    "CareerId" uuid,
    "FullName" character varying(160) NOT NULL,
    "Faculty" character varying(120),
    "Semester" smallint,
    "Email" character varying(180) NOT NULL,
    "Phone" character varying(40),
    CONSTRAINT "PK_students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_students_careers_CareerId" FOREIGN KEY ("CareerId") REFERENCES careers ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_students_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_roles (
    "UserId" uuid NOT NULL,
    "RoleId" smallint NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_user_roles_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE curriculum_courses (
    "CurriculumVersionId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "TermNumber" smallint,
    "IsMandatory" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_curriculum_courses" PRIMARY KEY ("CurriculumVersionId", "CourseId"),
    CONSTRAINT "FK_curriculum_courses_courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES courses ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_curriculum_courses_curriculum_versions_CurriculumVersionId" FOREIGN KEY ("CurriculumVersionId") REFERENCES curriculum_versions ("Id") ON DELETE CASCADE
);

CREATE TABLE course_offerings (
    "Id" uuid NOT NULL,
    "OfferingCode" character varying(30) NOT NULL,
    "CourseId" uuid NOT NULL,
    "CareerId" uuid NOT NULL,
    "ProfessorId" uuid,
    "Section" character varying(10) NOT NULL,
    "Term" character varying(20) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "SeatsTotal" integer NOT NULL,
    "SeatsTaken" integer NOT NULL,
    "CreatedByUserId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_course_offerings" PRIMARY KEY ("Id"),
    CONSTRAINT ck_course_offerings_seats_taken CHECK ("SeatsTaken" >= 0 AND "SeatsTaken" <= "SeatsTotal"),
    CONSTRAINT ck_course_offerings_seats_total CHECK ("SeatsTotal" > 0),
    CONSTRAINT "FK_course_offerings_careers_CareerId" FOREIGN KEY ("CareerId") REFERENCES careers ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_course_offerings_courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES courses ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_course_offerings_professors_ProfessorId" FOREIGN KEY ("ProfessorId") REFERENCES professors ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_course_offerings_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
);

CREATE TABLE teacher_availability_snapshots (
    "Id" uuid NOT NULL,
    "ProfessorId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Speciality" character varying(120),
    "CapturedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_teacher_availability_snapshots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_teacher_availability_snapshots_professors_ProfessorId" FOREIGN KEY ("ProfessorId") REFERENCES professors ("Id") ON DELETE CASCADE
);

CREATE TABLE academic_records (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "Period" character varying(20) NOT NULL,
    "Credits" smallint,
    "Grade" numeric(5,2) NOT NULL,
    "ResultStatus" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_academic_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_academic_records_courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES courses ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_academic_records_students_StudentId" FOREIGN KEY ("StudentId") REFERENCES students ("Id") ON DELETE CASCADE
);

CREATE TABLE report_requests (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "RequestType" character varying(40) NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "IssuedAt" timestamp with time zone,
    "LegacyImported" boolean NOT NULL DEFAULT FALSE,
    "DownloadUrl" character varying(512),
    CONSTRAINT "PK_report_requests" PRIMARY KEY ("Id"),
    CONSTRAINT ck_report_requests_issued CHECK ("LegacyImported" = true OR "IssuedAt" IS NOT NULL),
    CONSTRAINT "FK_report_requests_students_StudentId" FOREIGN KEY ("StudentId") REFERENCES students ("Id") ON DELETE CASCADE
);

CREATE TABLE student_curriculum_assignments (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "CurriculumVersionId" uuid NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_student_curriculum_assignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_student_curriculum_assignments_curriculum_versions_Curricul~" FOREIGN KEY ("CurriculumVersionId") REFERENCES curriculum_versions ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_student_curriculum_assignments_students_StudentId" FOREIGN KEY ("StudentId") REFERENCES students ("Id") ON DELETE CASCADE
);

CREATE TABLE enrollments (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "CourseOfferingId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL,
    "EnrolledAt" timestamp with time zone NOT NULL,
    "ClosedAt" timestamp with time zone,
    CONSTRAINT "PK_enrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_enrollments_course_offerings_CourseOfferingId" FOREIGN KEY ("CourseOfferingId") REFERENCES course_offerings ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_enrollments_students_StudentId" FOREIGN KEY ("StudentId") REFERENCES students ("Id") ON DELETE CASCADE
);

CREATE TABLE grade_entries (
    "Id" uuid NOT NULL,
    "CourseOfferingId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "DraftGrade" numeric(5,2),
    "PublishedGrade" numeric(5,2),
    "IsPublished" boolean NOT NULL DEFAULT FALSE,
    "UpdatedByUserId" uuid NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_grade_entries" PRIMARY KEY ("Id"),
    CONSTRAINT ck_grade_entries_draft CHECK ("DraftGrade" IS NULL OR ("DraftGrade" >= 0 AND "DraftGrade" <= 100)),
    CONSTRAINT ck_grade_entries_published CHECK ("PublishedGrade" IS NULL OR ("PublishedGrade" >= 0 AND "PublishedGrade" <= 100)),
    CONSTRAINT "FK_grade_entries_course_offerings_CourseOfferingId" FOREIGN KEY ("CourseOfferingId") REFERENCES course_offerings ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_grade_entries_students_StudentId" FOREIGN KEY ("StudentId") REFERENCES students ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_grade_entries_users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_academic_records_CourseId" ON academic_records ("CourseId");

CREATE INDEX "IX_academic_records_StudentId" ON academic_records ("StudentId");

CREATE UNIQUE INDEX "IX_careers_Code" ON careers ("Code");

CREATE UNIQUE INDEX "IX_careers_Name" ON careers ("Name");

CREATE UNIQUE INDEX "IX_course_equivalences_pair_left_pair_right" ON course_equivalences (pair_left, pair_right) WHERE "IsActive" = true;

CREATE INDEX "IX_course_equivalences_SourceCourseId_TargetCourseId_IsActive" ON course_equivalences ("SourceCourseId", "TargetCourseId", "IsActive");

CREATE INDEX "IX_course_equivalences_TargetCourseId" ON course_equivalences ("TargetCourseId");

CREATE INDEX "IX_course_offerings_CareerId_Status" ON course_offerings ("CareerId", "Status");

CREATE INDEX "IX_course_offerings_CourseId" ON course_offerings ("CourseId");

CREATE INDEX "IX_course_offerings_CreatedByUserId" ON course_offerings ("CreatedByUserId");

CREATE UNIQUE INDEX "IX_course_offerings_OfferingCode" ON course_offerings ("OfferingCode");

CREATE INDEX "IX_course_offerings_ProfessorId" ON course_offerings ("ProfessorId");

CREATE INDEX "IX_course_offerings_Status" ON course_offerings ("Status");

CREATE UNIQUE INDEX "IX_courses_Code" ON courses ("Code");

CREATE INDEX "IX_curriculum_courses_CourseId" ON curriculum_courses ("CourseId");

CREATE INDEX "IX_curriculum_courses_CurriculumVersionId" ON curriculum_courses ("CurriculumVersionId");

CREATE INDEX "IX_curriculum_versions_CareerId_IsActive" ON curriculum_versions ("CareerId", "IsActive");

CREATE UNIQUE INDEX "IX_curriculum_versions_CareerId_VersionCode" ON curriculum_versions ("CareerId", "VersionCode");

CREATE UNIQUE INDEX "IX_directors_DirectorCode" ON directors ("DirectorCode");

CREATE UNIQUE INDEX "IX_directors_UserId" ON directors ("UserId");

CREATE INDEX "IX_enrollments_CourseOfferingId" ON enrollments ("CourseOfferingId");

CREATE INDEX "IX_enrollments_StudentId" ON enrollments ("StudentId");

CREATE UNIQUE INDEX "IX_enrollments_StudentId_CourseOfferingId" ON enrollments ("StudentId", "CourseOfferingId");

CREATE INDEX "IX_grade_entries_CourseOfferingId" ON grade_entries ("CourseOfferingId");

CREATE UNIQUE INDEX "IX_grade_entries_CourseOfferingId_StudentId" ON grade_entries ("CourseOfferingId", "StudentId");

CREATE INDEX "IX_grade_entries_StudentId" ON grade_entries ("StudentId");

CREATE INDEX "IX_grade_entries_UpdatedByUserId" ON grade_entries ("UpdatedByUserId");

CREATE UNIQUE INDEX "IX_professors_ProfessorCode" ON professors ("ProfessorCode");

CREATE UNIQUE INDEX "IX_professors_UserId" ON professors ("UserId");

CREATE UNIQUE INDEX "IX_refresh_tokens_TokenHash" ON refresh_tokens ("TokenHash");

CREATE INDEX "IX_refresh_tokens_UserId" ON refresh_tokens ("UserId");

CREATE INDEX "IX_report_requests_RequestedAt" ON report_requests ("RequestedAt");

CREATE INDEX "IX_report_requests_StudentId" ON report_requests ("StudentId");

CREATE UNIQUE INDEX "IX_roles_Code" ON roles ("Code");

CREATE INDEX "IX_student_curriculum_assignments_CurriculumVersionId" ON student_curriculum_assignments ("CurriculumVersionId");

CREATE UNIQUE INDEX "IX_student_curriculum_assignments_StudentId" ON student_curriculum_assignments ("StudentId") WHERE "IsActive" = true;

CREATE INDEX "IX_student_curriculum_assignments_StudentId_IsActive" ON student_curriculum_assignments ("StudentId", "IsActive");

CREATE INDEX "IX_students_CareerId" ON students ("CareerId");

CREATE UNIQUE INDEX "IX_students_StudentCode" ON students ("StudentCode");

CREATE UNIQUE INDEX "IX_students_UserId" ON students ("UserId");

CREATE INDEX "IX_teacher_availability_snapshots_ProfessorId" ON teacher_availability_snapshots ("ProfessorId");

CREATE INDEX "IX_user_roles_RoleId" ON user_roles ("RoleId");

CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220044647_202602202240_InitialAcademicFlow', '9.0.9');

COMMIT;

