// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcesosAcademicos.Infrastructure.Persistence;

#nullable disable

namespace ProcesosAcademicos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220044647_202602202240_InitialAcademicFlow")]
    partial class _202602202240_InitialAcademicFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.AcademicRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Credits")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("academic_records", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Career", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("careers", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short?>("Credits")
                        .HasColumnType("smallint");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CourseEquivalence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EquivalenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SourceCourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("pair_left")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("LEAST(\"SourceCourseId\", \"TargetCourseId\")", true);

                    b.Property<Guid>("pair_right")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("GREATEST(\"SourceCourseId\", \"TargetCourseId\")", true);

                    b.HasKey("Id");

                    b.HasIndex("TargetCourseId");

                    b.HasIndex("pair_left", "pair_right")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SourceCourseId", "TargetCourseId", "IsActive");

                    b.ToTable("course_equivalences", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_equivalences_not_same", "\"SourceCourseId\" <> \"TargetCourseId\"");
                        });
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfferingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeatsTaken")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OfferingCode")
                        .IsUnique();

                    b.HasIndex("ProfessorId");

                    b.HasIndex("Status");

                    b.HasIndex("CareerId", "Status");

                    b.ToTable("course_offerings", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_offerings_seats_taken", "\"SeatsTaken\" >= 0 AND \"SeatsTaken\" <= \"SeatsTotal\"");

                            t.HasCheckConstraint("ck_course_offerings_seats_total", "\"SeatsTotal\" > 0");
                        });
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CurriculumCourse", b =>
                {
                    b.Property<Guid>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short?>("TermNumber")
                        .HasColumnType("smallint");

                    b.HasKey("CurriculumVersionId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CurriculumVersionId");

                    b.ToTable("curriculum_courses", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CareerId", "IsActive");

                    b.HasIndex("CareerId", "VersionCode")
                        .IsUnique();

                    b.ToTable("curriculum_versions", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.DirectorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Campus")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DirectorCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DirectorCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("directors", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "CourseOfferingId")
                        .IsUnique();

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.GradeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DraftGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("PublishedGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CourseOfferingId", "StudentId")
                        .IsUnique();

                    b.ToTable("grade_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_grade_entries_draft", "\"DraftGrade\" IS NULL OR (\"DraftGrade\" >= 0 AND \"DraftGrade\" <= 100)");

                            t.HasCheckConstraint("ck_grade_entries_published", "\"PublishedGrade\" IS NULL OR (\"PublishedGrade\" >= 0 AND \"PublishedGrade\" <= 100)");
                        });
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.ProfessorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ProfessorCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Speciality")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("professors", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LegacyImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("StudentId");

                    b.ToTable("report_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_requests_issued", "\"LegacyImported\" = true OR \"IssuedAt\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.StudentCurriculumAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumVersionId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("StudentId", "IsActive");

                    b.ToTable("student_curriculum_assignments", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CareerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<short?>("Semester")
                        .HasColumnType("smallint");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CareerId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.TeacherAvailabilitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Speciality")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("teacher_availability_snapshots", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.AcademicRecord", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Course", "Course")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.StudentProfile", "Student")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CourseEquivalence", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Course", "SourceCourse")
                        .WithMany("SourceEquivalences")
                        .HasForeignKey("SourceCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.Course", "TargetCourse")
                        .WithMany("TargetEquivalences")
                        .HasForeignKey("TargetCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCourse");

                    b.Navigation("TargetCourse");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CourseOffering", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Career", "Career")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.Course", "Course")
                        .WithMany("Offerings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.ProfessorProfile", "Professor")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Career");

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CurriculumCourse", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Course", "Course")
                        .WithMany("CurriculumCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("Courses")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CurriculumVersion");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CurriculumVersion", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Career", "Career")
                        .WithMany("CurriculumVersions")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.DirectorProfile", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "User")
                        .WithOne("DirectorProfile")
                        .HasForeignKey("ProcesosAcademicos.Domain.Entities.DirectorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.CourseOffering", "CourseOffering")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.StudentProfile", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.GradeEntry", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.CourseOffering", "CourseOffering")
                        .WithMany("GradeEntries")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Student");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.ProfessorProfile", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "User")
                        .WithOne("ProfessorProfile")
                        .HasForeignKey("ProcesosAcademicos.Domain.Entities.ProfessorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.ReportRequest", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.StudentProfile", "Student")
                        .WithMany("ReportRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.StudentCurriculumAssignment", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.StudentProfile", "Student")
                        .WithMany("CurriculumAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVersion");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Career", "Career")
                        .WithMany("Students")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("ProcesosAcademicos.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.TeacherAvailabilitySnapshot", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.ProfessorProfile", "Professor")
                        .WithMany("AvailabilitySnapshots")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ProcesosAcademicos.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosAcademicos.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Career", b =>
                {
                    b.Navigation("CourseOfferings");

                    b.Navigation("CurriculumVersions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Course", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("CurriculumCourses");

                    b.Navigation("Offerings");

                    b.Navigation("SourceEquivalences");

                    b.Navigation("TargetEquivalences");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CourseOffering", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GradeEntries");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.ProfessorProfile", b =>
                {
                    b.Navigation("AvailabilitySnapshots");

                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("CurriculumAssignments");

                    b.Navigation("Enrollments");

                    b.Navigation("ReportRequests");
                });

            modelBuilder.Entity("ProcesosAcademicos.Domain.Entities.User", b =>
                {
                    b.Navigation("DirectorProfile");

                    b.Navigation("ProfessorProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
